name: checker
run-name: ${{ github.actor }} made a pull request
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  just-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
        env:
          runner: ubuntu-latest

      - name: Run Checker
        run: cd Utils && php Checker.php
