name: checker
run-name: ${{ github.actor }} made a pull request
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  just-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
        env:
          runner: ubuntu-latest

      - name: Get diffs
        id: diffs
        if: github.event.pull_request && github.event.pull_request.merged == true
        run: |
          diff_explorers=$(git diff --name-only --diff-filter=ACMRT origin/master | grep "Explorers/" | sed "s/Explorers\///" | tr "\n" ",")
          echo "files=$diff_explorers" >> $GITHUB_OUTPUT

      - name: Run Checker
        run: php Utils/Checker.php --explorers=${{ steps.diffs.outputs.files || '' }}
